Регистрация:
<form action="/user/register" method="post">
    Имя: <input type="text" name="name"> <br>
	Емайл: <input type="text" name="email"> <br>
    Пароль: <input type="password" name="password"> <br>
	Повторите пароль: <input type="password" name="password_repeat"> <br>
    <input type="submit" value="Зарегистрироваться">
</form>
<br>
<br>

Войти
<form action="/user/login" method="post">
    Емайл: <input type="text" name="email"> <br>
    Пароль: <input type="password" name="password"> <br>
    <input type="submit" value="Войти">
</form>

<br>
<br>
<?php if($this->error): ?>
    <span style="color: red"><?=$this->error;?></span>
<?php endif; ?>
